import Link from 'next/link';
import Image from 'next/image';

import NewsTicker from './NewsTicker';
import Button from './Button';
import FourLinks from './FourLinks';

export default function Footer() {
  return (
    <div className='mt-24 w-full bg-black md:mt-48'>
      <NewsTicker variant={2} text={'Newsletter+++'} />
      <div className='mx-6 md:mx-10 lg:mx-20'>
        <div className='grid pb-16 pt-8 md:grid-cols-3 md:pb-32 md:pt-16 lg:grid-cols-2'>
          <h2 className='BIGTEXT mb-6 font-semibold uppercase text-white md:col-span-2 md:mb-0 lg:col-span-1'>
            Design news to your inbox
          </h2>
          <div className='flex w-full items-center justify-center'>
            <div className='block w-full items-center justify-center lg:flex'>
              <input
                type='email'
                className='mb-2 block h-12 w-full px-4 lg:m-0 lg:mr-3 lg:w-2/5'
                placeholder='Email'
              />
              <Button text={'Sign up'} variant={1} />
            </div>
          </div>
        </div>
        <div className='grid md:grid-cols-3'>
          <div className=''>
            <h1 className='text-2xl font-semibold uppercase text-white'>
              Erryf Magazine
            </h1>
          </div>
          <div className='md:col-span-2'>
            <div className='grid gap-4 md:grid-cols-3 md:gap-16'>
              <div className='mt-4'></div>
              <div className='mt-4'>
                <Link href={'/magazine'} className='mb-3 block text-white'>
                  Magazine
                </Link>
                <Link href={'/podcast'} className='mb-3 block text-white'>
                  Podcast
                </Link>
                <Link href={'/authors'} className='mb-3 block text-white'>
                  Authors
                </Link>
              </div>
              <div className='mt-4'>
                <h4 className='mb-3 text-white'>Styleguide</h4>
                <h4 className='mb-3 text-white'>Licensing</h4>
                <h4 className='mb-3 text-white'>Changelog</h4>
              </div>
            </div>
          </div>
        </div>
        <div className='mt-8 flex justify-between pb-8 md:mt-24 md:pb-16'>
          <h6 className='text-sm text-white'>
            © Coded by Flick - Designed by Pawel Gola - Photos from Unsplash -
            Text generated by ChatGPT
          </h6>
          <FourLinks />
        </div>
      </div>
    </div>
  );
}
